### ISSUE TITLE
Error compiling py3nj dependency

### ISSUE THREAD

**Issue by v1kko** [MALES-project/SpeckleCn2Profiler#46]
somewhere somehow the wheel for py3nj got lost.
[py3nj-0.2.1-cp310-cp310-linux_x86_64.zip](https://github.com/user-attachments/files/17187973/py3nj-0.2.1-cp310-cp310-linux_x86_64.zip)
(change .zip into .whl)

We should find a solution for this problem

**Comment by SCiarella** [comment]
This can be solved by installing `python3-dev` before `speckcn2`
